const data = [
  { image: '😁', text: 'grinning face with smiling eyes' },
  { image: '😂', text: 'face with tears of joy' },
  { image: '🙂', text: 'slightly smiling face' },
  { image: '🙃', text: 'upside-down face' },
  { image: '🤔', text: 'thinking face' },
  { image: '🤨', text: 'face with raised eyebrow' },
  { image: '🤯', text: 'exploding head' },
  { image: '😮', text: 'face with open mouth' },
  { image: '😎', text: 'smiling face with with sunglasses' },
  { image: '🤫', text: 'shushing face' },
  { image: '👻', text: 'ghost' },
  { image: '👽', text: 'alien' },
  { image: '👾', text: 'alien monster' },
  { image: '🤖', text: 'robot' },
  { image: '🙈', text: 'see-no-evil monkey' },
  { image: '🙉', text: 'hear-no-evil monkey' },
  { image: '🙊', text: 'speak-no-evil monkey' },
  { image: '👋', text: 'waving hand' },
  { image: '🖖', text: 'vulcan salute' },
  { image: '✌️', text: 'victory hand' },
  { image: '🤟', text: 'love-you gesture' },
  { image: '🤘', text: 'sign of the horns' },
  { image: '👍', text: 'thumbs up' },
  { image: '👊', text: 'oncoming fist' },
  { image: '🙌', text: 'raising hands' },
  { image: '🤝', text: 'handshake' },
  { image: '⛺', text: 'tent' },
  { image: '🚧', text: 'construction' },
  { image: '⛓️', text: 'chains' },
  { image: '💡', text: 'light bulb' },
  { image: '💭', text: 'thought ballon' },
  { image: '🚀', text: 'rocket' },
  { image: '🛸', text: 'flying saucer' },
  { image: '🗺️', text: 'world map' },
  { image: '☁️', text: 'cloud' },
  { image: '☃️', text: 'snowman' },
  { image: '🧊', text: 'ice' },
  { image: '🔥', text: 'fire' },
  { image: '💥', text: 'collision' },
  { image: '✨', text: 'sparkles' },
  { image: '🕸️', text: 'spider web' },
  { image: '🐛', text: 'bug' },
  { image: '🦋', text: 'butterfly' },
  { image: '🐣', text: 'hatching chick' },
  { image: '🔬', text: 'microscope' },
  { image: '🔭', text: 'telescope' },
  { image: '💻', text: 'laptop' },
  { image: '🖥️', text: 'desktop computer' },
  { image: '📱', text: 'mobile phone' },
  { image: '🎨', text: 'artist paletter' },
  { image: '🎁', text: 'wrapped gift' },
  { image: '🍦', text: 'soft ice cream' },
  { image: '🍉', text: 'watermelon' }
]

export default data
